@startuml "AVES - ajouter un produit"
!theme amiga

|#LightBlue|u| Gestionnaire fruits et légumes
start
|#SkyBlue|f| front
|#RoyalBlue|b| back

|u|
:se rend sur la page "Nos produits";
:clique sur le bouton "ajouter un produit";
|f|
:affiche la page "ajoutProduit";
repeat
repeat
|u|
:rempli les champs demandés;
|f|
repeatwhile(les données sont conformes aux règles du formulaire de nouveau produit) is(non) not(oui)
:transmet les informations au serveur;
|b|
repeatwhile(vérifie si les données sont conformes) is(non) not(oui)
:ajoute le nouveau produit à la base de données;
|f|
:Affiche le message "Le produit a bien été créé";

end

@enduml


@startuml "AVES - modifié un produit"
!theme amiga

|#LightBlue|u| Gestionnaire fruits et légumes
start
|#SkyBlue|f| front
|#RoyalBlue|b| back

|u|
:se rend sur la page "Nos produits";
:clique sur le bouton "modifier un produit";
|f|
:transmet la demande au serveur;
|b|
:importe les données liées au produit;
|f|
:affiche la page "modifierProduit" avec les champs pré-remplis;
repeat
repeat
|u|
:modifie les champs de données;
|f|
repeatwhile(les données sont conformes aux règles du formulaire de produit) is(non) not(oui)
:transmet les informations au serveur;
|b|
repeatwhile(vérifie si les données sont conformes) is(non) not(oui)
:modifie les données du produit dans la base de données;
|f|
:Affiche le message "Ce produit a bien été modifié";

end

@enduml


@startuml "AVES - supprimer un produit"
!theme amiga

|#LightBlue|u| Gestionnaire fruits et légumes
start
|#SkyBlue|f| front
|#RoyalBlue|b| back

|u|
:se rend sur la page "Nos produits";
:clique sur le bouton "supprimer un produit";
|f|
:affiche le message "êtes-vous sur de vouloir supprimer ce produit ?";
|u|
if(choisi de cliquer sur :) is(oui) then
|f|
:transmet les données au server;
|b|
:efface les données du produit de la base de données;
|f|
:Affiche "produit supprimé";
else(non)
|f|
:Affiche la page des produits;
endif

end

@enduml
