@startuml
title "Diagramme de classe du site AVES"
!theme materia


Class a as "admin" {

    droitsSupplémentaires :string

}

Class g as "gestionnaire" {

    nom : string
    prénom: : string
    tel : int
    mail : string
    mot de passe : string

}

Class fel as "Fruits et légumes" {

    nom : string
    variété : string
    quantité : float
    date de récolte : date

}

class pa as "Panier" {

    nombre : int
    date du panier : date

}

Class fin as "Financier"{

    logo : string
    lien : string

}

Class fo as "formulaire de contact" {

    nom : string
    prénom: : string
    mail : string
    tel : int
    contenu : string

}

a "1" -- "n" fo : réceptionne
fel "n" -- "n" pa : compose
g "n" -left- "n" fel : organise
g "n" -- "n" fin : gère

a --|> g : hérite de


@enduml