@startuml
title "Diagramme de classe du site AVES"
!theme materia


Class g as "gestionnaire" {

    nom : string
    prénom: : string
    role : string
    mail : string
    mot de passe : string

}

Class fel as "Fruits et légumes" {

    nom : string
    variété : string
    recette : string

}

class pa as "Panier" {

    nom : string
    prix : float

}

Class fin as "Financeur"{

    logo : string
    lien : string

}

Class fo as "formulaire de contact" {

    nom : string
    prénom: : string
    mail : string
    tel : int
    contenu : string

}

g "1" -- "n" fo : réceptionne
fel "n" -- "1" pa : compose
g "1" -- "n" pa : créé
g "1" -left- "n" fel : organise
g "1" -- "n" fin : gère



@enduml